# Generated by Django 6.0.1 on 2026-03-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_status_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='symptom',
        ),
    ]
